packages:
  - apps/*
  - packages/*
  - '!apps/web-erp-old'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
